#!/bin/bash

# Set JWT token
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhVmFsdWVzIjp7ImlkIjo5LCJuYW1lIjoiUHJvZHVjdE93bmVyIiwicGFzc3dvcmQiOiIkMmEkMTAka3dueGE4NS9zR3BDZ1FlemFidjdrZXVvRlVKSXg1SS4zYnlZSnRxUUJxRy5rdlIvU2h5RnUiLCJyb2xlIjoicHJvZHVjdF9vd25lciJ9LCJfcHJldmlvdXNEYXRhVmFsdWVzIjp7ImlkIjo5LCJuYW1lIjoiUHJvZHVjdE93bmVyIiwicGFzc3dvcmQiOiIkMmEkMTAka3dueGE4NS9zR3BDZ1FlemFidjdrZXVvRlVKSXg1SS4zYnlZSnRxUUJxRy5rdlIvU2h5RnUiLCJyb2xlIjoicHJvZHVjdF9vd25lciJ9LCJ1bmlxbm8iOjEsIl9jaGFuZ2VkIjp7fSwiX29wdGlvbnMiOnsiaXNOZXdSZWNvcmQiOmZhbHNlLCJfc2NoZW1hIjpudWxsLCJfc2NoZW1hRGVsaW1pdGVyIjoiIiwicmF3Ijp0cnVlLCJhdHRyaWJ1dGVzIjpbImlkIiwibmFtZSIsInBhc3N3b3JkIiwicm9sZSJdfSwiaXNOZXdSZWNvcmQiOmZhbHNlLCJpYXQiOjE2NzYyNjI2NzQsImV4cCI6MTY3Njg2NzQ3NH0.z20H5mqPVxiT1PfQtpOf1NxZupPBVQEG9Adn-tS6cy0"

# Set header in curl request
curl -X POST -H "Authorization: $TOKEN" http://localhost:3000/cpf


